### ISSUE TITLE
Freeze and eventual crash when loading a new chunk in 0.8.0

### ISSUE THREAD

**Issue by TrueCP6** [SuperCoder7979/ecotones#17]
```
[13:43:13] [Server thread/ERROR]: Encountered an unexpected exception
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-1.17.1.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:550) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_4660.method_23469(class_4660.java:36) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2944.method_23381(class_2944.java:159) ~[intermediary-1.17.1.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[guava-21.0.jar:?]
	at net.minecraft.class_2944.method_13151(class_2944.java:159) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2988.method_30384(class_2988.java:29) ~[intermediary-1.17.1.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_2988.method_13151(class_2988.java:28) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2988.method_30384(class_2988.java:29) ~[intermediary-1.17.1.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_2988.method_13151(class_2988.java:28) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2988.method_30384(class_2988.java:29) ~[intermediary-1.17.1.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_2988.method_13151(class_2988.java:28) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1959.method_8702(class_1959.java:388) ~[intermediary-1.17.1.jar:?]
	at supercoder79.ecotones.world.gen.EcotonesChunkGenerator.method_12102(EcotonesChunkGenerator.java:288) ~[ecotones-0.8.0.jar:?]
	at net.minecraft.class_2806.method_12151(class_2806.java:100) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:231) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:556) ~[intermediary-1.17.1.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:550) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
[13:43:13] [Worker-Main-9/WARN]: Worker-Main-9 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-1.17.1.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:550) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_4660.method_23469(class_4660.java:36) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2944.method_23381(class_2944.java:159) ~[intermediary-1.17.1.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[guava-21.0.jar:?]
	at net.minecraft.class_2944.method_13151(class_2944.java:159) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2988.method_30384(class_2988.java:29) ~[intermediary-1.17.1.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_2988.method_13151(class_2988.java:28) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2988.method_30384(class_2988.java:29) ~[intermediary-1.17.1.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_2988.method_13151(class_2988.java:28) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2988.method_30384(class_2988.java:29) ~[intermediary-1.17.1.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_2988.method_13151(class_2988.java:28) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1959.method_8702(class_1959.java:388) ~[intermediary-1.17.1.jar:?]
	at supercoder79.ecotones.world.gen.EcotonesChunkGenerator.method_12102(EcotonesChunkGenerator.java:288) ~[ecotones-0.8.0.jar:?]
	at net.minecraft.class_2806.method_12151(class_2806.java:100) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:231) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:556) ~[intermediary-1.17.1.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:550) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
```
Mod list:
```
[13:36:04] [main/INFO]: [FabricLoader] Loading 65 mods:
	- advanced_runtime_resource_pack@0.3.10
	- architectury@2.2.21
	- cloth-armor-api-v1@1.5.47
	- cloth-basic-math@0.5.1
	- cloth-common-events-v1@1.5.47
	- cloth-config2@5.0.34
	- ecotones@0.8.0
	- fabric@0.37.0+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+b246072f13
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.2+6cefd57718
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.12+6cefd57718
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.1.0-pre.01+0c19b33818
	- fabricloader@0.11.6
	- fasttransferlib@0.5.6
	- fiber@0.23.0-2
	- java@16
	- lithium@0.7.3
	- magna@1.5.5-1.17-pre4
	- minecraft@1.17.1
	- modern_industrialization@0.5.2-alpha.03
	- modmenu@2.0.2
	- patchouli@1.17-52-FABRIC-SNAPSHOT
	- roughlyenoughitems@6.0.264-alpha
	- sodium@0.3.0+build.5
	- team_reborn_energy@0.1.1
```

**Comment by SuperCoder7979** [comment]
Should be fixed with 0.8.1!
